version: '3.7'

services:
  db:
    image: postgres:13.2
    volumes:
      - ./docker/db:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    expose:
      - 5432
    environment:
      - POSTGRES_DB=verceldb
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=mULFz7hC1QcX
    ports:
      - "5433:5432"
    restart: unless-stopped

  alembic:
    image: fastapi-base:latest
    environment:
      SQL_DATABASE_URL: 'postgres://default:mULFz7hC1QcX@ep-shrill-queen-a1y4f8fx-pooler.ap-southeast-1.aws.neon.tech:5432/verceldb'
      SECRET_KEY: ${SECRET_KEY}
    command: [ "alembic", "upgrade", "head" ]
    depends_on:
      - db

  app:
    image: fastapi-base:latest
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      SQL_DATABASE_URL: 'postgres://default:mULFz7hC1QcX@ep-shrill-queen-a1y4f8fx-pooler.ap-southeast-1.aws.neon.tech:5432/verceldb'
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - db
      - alembic